/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsi14.sastra.edu)
#  Generated on:      Fri Dec 12 11:58:53 2025
#  Design:            sa
#  Command:           saveNetlist sa_route_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 12 2025 11:43:56 IST (Dec 12 2025 06:13:56 UTC)
// Verification Directory fv/sa 
module sa (
	clk, 
	rst, 
	a, 
	b, 
	load, 
	co, 
	sum, 
	done);
   input clk;
   input rst;
   input [3:0] a;
   input [3:0] b;
   input load;
   output co;
   output sum;
   output done;

   // Internal wires
   wire [3:0] a_reg;
   wire [3:0] b_reg;
   wire [2:0] count;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;

   DFFQX1 sum_reg (.CK(clk),
	.D(n_37),
	.Q(sum));
   DFFQX1 \a_reg_reg[1]  (.CK(clk),
	.D(n_33),
	.Q(a_reg[1]));
   DFFQX1 \b_reg_reg[2]  (.CK(clk),
	.D(n_29),
	.Q(b_reg[2]));
   DFFQX1 \a_reg_reg[2]  (.CK(clk),
	.D(n_31),
	.Q(a_reg[2]));
   DFFQX1 co_reg (.CK(clk),
	.D(n_32),
	.Q(co));
   DFFQX1 \b_reg_reg[1]  (.CK(clk),
	.D(n_36),
	.Q(b_reg[1]));
   DFFQX1 \count_reg[1]  (.CK(clk),
	.D(n_30),
	.Q(count[1]));
   DFFQX1 \b_reg_reg[0]  (.CK(clk),
	.D(n_35),
	.Q(b_reg[0]));
   DFFQX1 \a_reg_reg[0]  (.CK(clk),
	.D(n_34),
	.Q(a_reg[0]));
   AO22XL g995__2398 (.A0(n_12),
	.A1(n_27),
	.B0(sum),
	.B1(n_25),
	.Y(n_37));
   DFFQX1 \count_reg[0]  (.CK(clk),
	.D(n_24),
	.Q(count[0]));
   CLKINVX1 g1009 (.A(n_19),
	.Y(n_36));
   CLKINVX1 g1007 (.A(n_26),
	.Y(n_35));
   CLKINVX1 g1008 (.A(n_21),
	.Y(n_34));
   CLKINVX1 g1010 (.A(n_18),
	.Y(n_33));
   CLKINVX1 g1000 (.A(n_28),
	.Y(n_32));
   CLKINVX1 g1001 (.A(n_17),
	.Y(n_31));
   OAI31XL g1012__5107 (.A0(n_22),
	.A1(count[1]),
	.A2(n_23),
	.B0(n_15),
	.Y(n_30));
   CLKINVX1 g1011 (.A(n_16),
	.Y(n_29));
   DFFQX1 \b_reg_reg[3]  (.CK(clk),
	.D(n_13),
	.Q(b_reg[3]));
   DFFQX1 \a_reg_reg[3]  (.CK(clk),
	.D(n_14),
	.Q(a_reg[3]));
   AOI32X1 g1002__6260 (.A0(a_reg[0]),
	.A1(b_reg[0]),
	.A2(n_27),
	.B0(co),
	.B1(n_8),
	.Y(n_28));
   AOI222XL g1013__4319 (.A0(n_25),
	.A1(b_reg[0]),
	.B0(b_reg[1]),
	.B1(n_27),
	.C0(b[0]),
	.C1(n_20),
	.Y(n_26));
   OAI22XL g1024__8428 (.A0(n_23),
	.A1(count[0]),
	.B0(n_10),
	.B1(n_22),
	.Y(n_24));
   AOI222XL g1014__5526 (.A0(n_25),
	.A1(a_reg[0]),
	.B0(a_reg[1]),
	.B1(n_27),
	.C0(a[0]),
	.C1(n_20),
	.Y(n_21));
   AOI222XL g1015__6783 (.A0(n_25),
	.A1(b_reg[1]),
	.B0(b_reg[2]),
	.B1(n_27),
	.C0(b[1]),
	.C1(n_20),
	.Y(n_19));
   DFFQXL done_reg (.CK(clk),
	.D(n_9),
	.Q(done));
   AOI222XL g1016__3680 (.A0(n_25),
	.A1(a_reg[1]),
	.B0(a_reg[2]),
	.B1(n_27),
	.C0(a[1]),
	.C1(n_20),
	.Y(n_18));
   AOI222XL g1003__1617 (.A0(n_25),
	.A1(a_reg[2]),
	.B0(a_reg[3]),
	.B1(n_27),
	.C0(a[2]),
	.C1(n_20),
	.Y(n_17));
   AOI222XL g1017__2802 (.A0(n_25),
	.A1(b_reg[2]),
	.B0(b_reg[3]),
	.B1(n_27),
	.C0(b[2]),
	.C1(n_20),
	.Y(n_16));
   DFFQX1 \count_reg[2]  (.CK(clk),
	.D(n_11),
	.Q(count[2]));
   OAI21X1 g1019__1705 (.A0(n_5),
	.A1(n_25),
	.B0(count[1]),
	.Y(n_15));
   AO22XL g1021__5122 (.A0(a_reg[3]),
	.A1(n_25),
	.B0(a[3]),
	.B1(n_20),
	.Y(n_14));
   AO22XL g1022__8246 (.A0(b_reg[3]),
	.A1(n_25),
	.B0(b[3]),
	.B1(n_20),
	.Y(n_13));
   OAI21XL g1023__7098 (.A0(b_reg[0]),
	.A1(n_6),
	.B0(n_7),
	.Y(n_12));
   NAND2XL g1027__6131 (.A(n_4),
	.B(n_10),
	.Y(n_11));
   NOR3XL g1028__1881 (.A(count[0]),
	.B(count[1]),
	.C(n_10),
	.Y(n_9));
   NAND2XL g1025__5115 (.A(n_2),
	.B(n_10),
	.Y(n_8));
   NAND2XL g1026__7482 (.A(b_reg[0]),
	.B(n_6),
	.Y(n_7));
   CLKINVX1 g1029 (.A(n_27),
	.Y(n_23));
   NOR2XL g1031__4733 (.A(count[0]),
	.B(n_3),
	.Y(n_5));
   CLKINVX1 g1030 (.A(n_10),
	.Y(n_25));
   NAND3X1 g1035__6161 (.A(count[0]),
	.B(count[1]),
	.C(n_1),
	.Y(n_4));
   NOR2X1 g1032__9315 (.A(count[2]),
	.B(n_3),
	.Y(n_27));
   OAI21X1 g1034__9945 (.A0(a_reg[0]),
	.A1(b_reg[0]),
	.B0(n_1),
	.Y(n_2));
   OAI21X1 g1036__2883 (.A0(a_reg[0]),
	.A1(co),
	.B0(n_0),
	.Y(n_6));
   NAND2X1 g1033__2346 (.A(count[2]),
	.B(n_1),
	.Y(n_10));
   CLKINVX1 g1037 (.A(n_1),
	.Y(n_3));
   NOR2X2 g1038__1666 (.A(load),
	.B(rst),
	.Y(n_1));
   NAND2XL g1039__7410 (.A(a_reg[0]),
	.B(co),
	.Y(n_0));
   NOR2BX1 g1040__6417 (.AN(load),
	.B(rst),
	.Y(n_20));
   CLKINVX1 g1041 (.A(count[0]),
	.Y(n_22));
endmodule

